### PR TITLE
[DM-39905] Get datalinker build working

### PR DESCRIPTION
**Pull request by cbanek**
First, safir now requires python 3.11, so
to get to any version above 3.8.0, you need
to change the tox.ini to force it to require
python 3.11.  Previously tox.ini was using
the system python and not forcing to python3.11
even if it was installed.  Then safir would
fail to install.

Also update the dependencies in the requirements
directory.

### CODE REVIEW

**Comment by cbanek** [comment]
Not sure what's up with the giant python dependency map, they all look to me like they have pinned hashes. 

It's complaining about:
    # via
    #   boto3
    #   botocore
lsst-daf-butler[postgres]==25.2023.2700 \
    --hash=sha256:bb9e82ce19973eba7db2159e36eaee371804415dc50bc0d8c071d4590e289583 \
    --hash=sha256:d7feb47e3a97138678885eccfeb3ac565a1b61547740b0f335defea9df4a7bb6

And lsst-resources is also pinned:

    # via lsst-daf-butler
lsst-resources[gs,s3]==25.2023.2700 \
    --hash=sha256:ef1cefa613e0b9ba42bf1284f8ea525c02b262f41c247da7666a2c61b207e7fe \
    --hash=sha256:f9a3146709f24ad1beef24c40e31c9d5ee5f2d112e8f95eabbb69ff87eecb094

**Review by rra — APPROVED** [review]
Looks harmless to me, although it's possibly worth noting that we've been assuming Python 3.11 is the default Python in all our various packages and I think most people have set up their local systems that way, so you're likely to run into this with other services as well. Might be worth a stand-up discussion whether we want to make this more explicit (and possibly automate the changes required when switching to a new Python release).

**Comment by rra** [comment]
I'm not sure what's going on with lsst-resources in the Docker build. It looks like it's pulling in an alpha version that conflicts with the lsst-daf-butler dependency, but I don't know why it's doing that given that its version is pinned.

**Comment by cbanek** [comment]
Yeah I've got python 3.11 installed but tox kept using python 3.10 for some reason.  Even when I had a virtualenv with 3.11 tox kept on using the system python of 3.10.  Is it possible my system is misconfigured somehow?  I'm running ubuntu 22.04 so the system python seems to be 3.10.  Is your system python 3.11 and everything assumes that?

**Pull request closed without merging**
